/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ProofTrack {
  export type ProductStruct = {
    id: string;
    name: string;
    manufacturer: string;
    category: string;
    description: string;
    currentOwner: AddressLike;
    createdAt: BigNumberish;
    exists: boolean;
  };

  export type ProductStructOutput = [
    id: string,
    name: string,
    manufacturer: string,
    category: string,
    description: string,
    currentOwner: string,
    createdAt: bigint,
    exists: boolean
  ] & {
    id: string;
    name: string;
    manufacturer: string;
    category: string;
    description: string;
    currentOwner: string;
    createdAt: bigint;
    exists: boolean;
  };

  export type HistoryEventStruct = {
    eventType: string;
    from: AddressLike;
    to: AddressLike;
    timestamp: BigNumberish;
    location: string;
    note: string;
  };

  export type HistoryEventStructOutput = [
    eventType: string,
    from: string,
    to: string,
    timestamp: bigint,
    location: string,
    note: string
  ] & {
    eventType: string;
    from: string;
    to: string;
    timestamp: bigint;
    location: string;
    note: string;
  };
}

export interface ProofTrackInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createProduct"
      | "getProduct"
      | "getProductHistory"
      | "productHistories"
      | "products"
      | "transferProduct"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProductCreated" | "ProductTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createProduct",
    values: [string, string, string, string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "getProduct", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getProductHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "productHistories",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "products", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferProduct",
    values: [string, AddressLike, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProductHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "productHistories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferProduct",
    data: BytesLike
  ): Result;
}

export namespace ProductCreatedEvent {
  export type InputTuple = [
    productId: string,
    manufacturer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: string,
    manufacturer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: string;
    manufacturer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductTransferredEvent {
  export type InputTuple = [
    productId: string,
    from: AddressLike,
    to: AddressLike,
    location: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: string,
    from: string,
    to: string,
    location: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: string;
    from: string;
    to: string;
    location: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProofTrack extends BaseContract {
  connect(runner?: ContractRunner | null): ProofTrack;
  waitForDeployment(): Promise<this>;

  interface: ProofTrackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProduct: TypedContractMethod<
    [
      _id: string,
      _name: string,
      _manufacturer: string,
      _category: string,
      _description: string,
      _location: string
    ],
    [void],
    "nonpayable"
  >;

  getProduct: TypedContractMethod<
    [_id: string],
    [ProofTrack.ProductStructOutput],
    "view"
  >;

  getProductHistory: TypedContractMethod<
    [_id: string],
    [ProofTrack.HistoryEventStructOutput[]],
    "view"
  >;

  productHistories: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, string, bigint, string, string] & {
        eventType: string;
        from: string;
        to: string;
        timestamp: bigint;
        location: string;
        note: string;
      }
    ],
    "view"
  >;

  products: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        id: string;
        name: string;
        manufacturer: string;
        category: string;
        description: string;
        currentOwner: string;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  transferProduct: TypedContractMethod<
    [_id: string, _to: AddressLike, _location: string, _note: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProduct"
  ): TypedContractMethod<
    [
      _id: string,
      _name: string,
      _manufacturer: string,
      _category: string,
      _description: string,
      _location: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [_id: string],
    [ProofTrack.ProductStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProductHistory"
  ): TypedContractMethod<
    [_id: string],
    [ProofTrack.HistoryEventStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "productHistories"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, string, bigint, string, string] & {
        eventType: string;
        from: string;
        to: string;
        timestamp: bigint;
        location: string;
        note: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        id: string;
        name: string;
        manufacturer: string;
        category: string;
        description: string;
        currentOwner: string;
        createdAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferProduct"
  ): TypedContractMethod<
    [_id: string, _to: AddressLike, _location: string, _note: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProductCreated"
  ): TypedContractEvent<
    ProductCreatedEvent.InputTuple,
    ProductCreatedEvent.OutputTuple,
    ProductCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProductTransferred"
  ): TypedContractEvent<
    ProductTransferredEvent.InputTuple,
    ProductTransferredEvent.OutputTuple,
    ProductTransferredEvent.OutputObject
  >;

  filters: {
    "ProductCreated(string,address,uint256)": TypedContractEvent<
      ProductCreatedEvent.InputTuple,
      ProductCreatedEvent.OutputTuple,
      ProductCreatedEvent.OutputObject
    >;
    ProductCreated: TypedContractEvent<
      ProductCreatedEvent.InputTuple,
      ProductCreatedEvent.OutputTuple,
      ProductCreatedEvent.OutputObject
    >;

    "ProductTransferred(string,address,address,string,uint256)": TypedContractEvent<
      ProductTransferredEvent.InputTuple,
      ProductTransferredEvent.OutputTuple,
      ProductTransferredEvent.OutputObject
    >;
    ProductTransferred: TypedContractEvent<
      ProductTransferredEvent.InputTuple,
      ProductTransferredEvent.OutputTuple,
      ProductTransferredEvent.OutputObject
    >;
  };
}
